package com.base.dao;

import com.base.bean.DealDeviceCost;
import java.util.List;

public interface DealDeviceCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealdevicecost
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealdevicecost
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    int insert(DealDeviceCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealdevicecost
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    DealDeviceCost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealdevicecost
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    List<DealDeviceCost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealdevicecost
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    int updateByPrimaryKey(DealDeviceCost record);
    
    List<DealDeviceCost> selectByDealId(Integer deal_id);
}