package com.base.dao;

import com.base.bean.DealTrouble;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DealTroubleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealtrouble
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealtrouble
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    int insert(DealTrouble record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealtrouble
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    DealTrouble selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealtrouble
     * @param dept_id 
     * @param endTime 
     * @param startTime 
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    List<DealTrouble> selectAll(@Param("startTime")String startTime, @Param("endTime")String endTime, @Param("dept_id")Integer dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealtrouble
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    int updateByPrimaryKey(DealTrouble record);
    
    
    List<DealTrouble> getDealTroubleByState(@Param("state")Integer[] state);
}