package com.base.dao;

import com.base.bean.DeviceType;
import java.util.List;

public interface DeviceTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_devicetype
     *
     * @mbg.generated Tue Oct 16 14:11:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_devicetype
     *
     * @mbg.generated Tue Oct 16 14:11:01 CST 2018
     */
    int insert(DeviceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_devicetype
     *
     * @mbg.generated Tue Oct 16 14:11:01 CST 2018
     */
    DeviceType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_devicetype
     *
     * @mbg.generated Tue Oct 16 14:11:01 CST 2018
     */
    List<DeviceType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_devicetype
     *
     * @mbg.generated Tue Oct 16 14:11:01 CST 2018
     */
    int updateByPrimaryKey(DeviceType record);
}