package com.base.dao;

import com.base.bean.Device;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_device
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_device
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_device
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    Device selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_device
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    List<Device> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_device
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    int updateByPrimaryKey(Device record);

	List<Device> selectDeviceListByType(@Param("type_id")Integer type_id);
}