package com.base.dao;

import com.base.bean.RoleUser;
import java.util.List;

public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_user
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_user
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    int insert(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_user
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    RoleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_user
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    List<RoleUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_user
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    int updateByPrimaryKey(RoleUser record);
}