package com.base.dao;

import com.base.bean.Role;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.PatchMapping;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     * @param regionId 
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    List<Role> selectAll(@Param("regionId")Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    int updateByPrimaryKey(Role record);
}