package com.base.bean;

public class DealDeviceCost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealdevicecost.ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealdevicecost.DEAL_ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    private Integer dealId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealdevicecost.DEVICE_ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealdevicecost.TOTAL_COST
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    private String totalCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealdevicecost.COUNT
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    private String count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealdevicecost.ID
     *
     * @return the value of base_dealdevicecost.ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealdevicecost.ID
     *
     * @param id the value for base_dealdevicecost.ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealdevicecost.DEAL_ID
     *
     * @return the value of base_dealdevicecost.DEAL_ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealdevicecost.DEAL_ID
     *
     * @param dealId the value for base_dealdevicecost.DEAL_ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealdevicecost.DEVICE_ID
     *
     * @return the value of base_dealdevicecost.DEVICE_ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealdevicecost.DEVICE_ID
     *
     * @param deviceId the value for base_dealdevicecost.DEVICE_ID
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealdevicecost.TOTAL_COST
     *
     * @return the value of base_dealdevicecost.TOTAL_COST
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public String getTotalCost() {
        return totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealdevicecost.TOTAL_COST
     *
     * @param totalCost the value for base_dealdevicecost.TOTAL_COST
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public void setTotalCost(String totalCost) {
        this.totalCost = totalCost == null ? null : totalCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealdevicecost.COUNT
     *
     * @return the value of base_dealdevicecost.COUNT
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealdevicecost.COUNT
     *
     * @param count the value for base_dealdevicecost.COUNT
     *
     * @mbg.generated Thu Oct 18 10:01:57 CST 2018
     */
    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    private Device device;

	public Device getDevice() {
		return device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@Override
	public String toString() {
		return "DealDeviceCost [id=" + id + ", dealId=" + dealId + ", deviceId=" + deviceId + ", totalCost=" + totalCost
				+ ", count=" + count + ", device=" + device + "]";
	}
    
    
    
    
    
    
    
}