package com.base.bean;

import java.util.List;

public class DealTrouble {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.DEPT_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.REMARK
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.STARE
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.CREATE_TIME
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.RQ1
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private String rq1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.CREATE_USER_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.FIX_USER_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private Integer fixUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.RQ2
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private String rq2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.REASON
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.TOTAL_COST
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private String totalCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealtrouble.VISIT_REMARK
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    private String visitRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.ID
     *
     * @return the value of base_dealtrouble.ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.ID
     *
     * @param id the value for base_dealtrouble.ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.DEPT_ID
     *
     * @return the value of base_dealtrouble.DEPT_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.DEPT_ID
     *
     * @param deptId the value for base_dealtrouble.DEPT_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.REMARK
     *
     * @return the value of base_dealtrouble.REMARK
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.REMARK
     *
     * @param remark the value for base_dealtrouble.REMARK
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.STARE
     *
     * @return the value of base_dealtrouble.STARE
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.STARE
     *
     * @param stare the value for base_dealtrouble.STARE
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.CREATE_TIME
     *
     * @return the value of base_dealtrouble.CREATE_TIME
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.CREATE_TIME
     *
     * @param createTime the value for base_dealtrouble.CREATE_TIME
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.RQ1
     *
     * @return the value of base_dealtrouble.RQ1
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public String getRq1() {
        return rq1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.RQ1
     *
     * @param rq1 the value for base_dealtrouble.RQ1
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setRq1(String rq1) {
        this.rq1 = rq1 == null ? null : rq1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.CREATE_USER_ID
     *
     * @return the value of base_dealtrouble.CREATE_USER_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.CREATE_USER_ID
     *
     * @param createUserId the value for base_dealtrouble.CREATE_USER_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.FIX_USER_ID
     *
     * @return the value of base_dealtrouble.FIX_USER_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public Integer getFixUserId() {
        return fixUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.FIX_USER_ID
     *
     * @param fixUserId the value for base_dealtrouble.FIX_USER_ID
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setFixUserId(Integer fixUserId) {
        this.fixUserId = fixUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.RQ2
     *
     * @return the value of base_dealtrouble.RQ2
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public String getRq2() {
        return rq2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.RQ2
     *
     * @param rq2 the value for base_dealtrouble.RQ2
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setRq2(String rq2) {
        this.rq2 = rq2 == null ? null : rq2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.REASON
     *
     * @return the value of base_dealtrouble.REASON
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.REASON
     *
     * @param reason the value for base_dealtrouble.REASON
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.TOTAL_COST
     *
     * @return the value of base_dealtrouble.TOTAL_COST
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public String getTotalCost() {
        return totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.TOTAL_COST
     *
     * @param totalCost the value for base_dealtrouble.TOTAL_COST
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setTotalCost(String totalCost) {
        this.totalCost = totalCost == null ? null : totalCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealtrouble.VISIT_REMARK
     *
     * @return the value of base_dealtrouble.VISIT_REMARK
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public String getVisitRemark() {
        return visitRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealtrouble.VISIT_REMARK
     *
     * @param visitRemark the value for base_dealtrouble.VISIT_REMARK
     *
     * @mbg.generated Thu Oct 18 15:11:56 CST 2018
     */
    public void setVisitRemark(String visitRemark) {
        this.visitRemark = visitRemark == null ? null : visitRemark.trim();
    }
    
    private Integer ifdelete;
    private Department dept;
    private User createUser;
    private User fixUser;
    private List<DealDeviceCost> deviceCost;

    
    
	public Integer getIfdelete() {
		return ifdelete;
	}

	public void setIfdelete(Integer ifdelete) {
		this.ifdelete = ifdelete;
	}

	public Department getDept() {
		return dept;
	}

	public void setDept(Department dept) {
		this.dept = dept;
	}

	public User getCreateUser() {
		return createUser;
	}

	public void setCreateUser(User createUser) {
		this.createUser = createUser;
	}

	public User getFixUser() {
		return fixUser;
	}

	public void setFixUser(User fixUser) {
		this.fixUser = fixUser;
	}

	public List<DealDeviceCost> getDeviceCost() {
		return deviceCost;
	}

	public void setDeviceCost(List<DealDeviceCost> deviceCost) {
		this.deviceCost = deviceCost;
	}
    
    
    
    
    
}