package com.base.bean;

public class Device {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_device.ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_device.TYPE_ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_device.PRICE
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_device.NAME
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_device.RERAMK
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_device.IFDELETE
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    private Integer ifdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_device.USER_ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_device.ID
     *
     * @return the value of base_device.ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_device.ID
     *
     * @param id the value for base_device.ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_device.TYPE_ID
     *
     * @return the value of base_device.TYPE_ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_device.TYPE_ID
     *
     * @param typeId the value for base_device.TYPE_ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_device.PRICE
     *
     * @return the value of base_device.PRICE
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_device.PRICE
     *
     * @param price the value for base_device.PRICE
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_device.NAME
     *
     * @return the value of base_device.NAME
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_device.NAME
     *
     * @param name the value for base_device.NAME
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_device.RERAMK
     *
     * @return the value of base_device.RERAMK
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_device.RERAMK
     *
     * @param reramk the value for base_device.RERAMK
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_device.IFDELETE
     *
     * @return the value of base_device.IFDELETE
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public Integer getIfdelete() {
        return ifdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_device.IFDELETE
     *
     * @param ifdelete the value for base_device.IFDELETE
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public void setIfdelete(Integer ifdelete) {
        this.ifdelete = ifdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_device.USER_ID
     *
     * @return the value of base_device.USER_ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_device.USER_ID
     *
     * @param userId the value for base_device.USER_ID
     *
     * @mbg.generated Tue Oct 16 15:44:46 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    private User createUser;
    private DeviceType deviceType;

    private Integer sort;
	public User getCreateUser() {
		return createUser;
	}

	public void setCreateUser(User createUser) {
		this.createUser = createUser;
	}

	public DeviceType getDeviceType() {
		return deviceType;
	}

	public void setDeviceType(DeviceType deviceType) {
		this.deviceType = deviceType;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}
    
    
}