package com.base.bean;

public class RoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_menu.ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_menu.CATALOG_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    private Integer catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_menu.ROLE_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_menu.ID
     *
     * @return the value of base_role_menu.ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_menu.ID
     *
     * @param id the value for base_role_menu.ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_menu.CATALOG_ID
     *
     * @return the value of base_role_menu.CATALOG_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_menu.CATALOG_ID
     *
     * @param catalogId the value for base_role_menu.CATALOG_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_menu.ROLE_ID
     *
     * @return the value of base_role_menu.ROLE_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_menu.ROLE_ID
     *
     * @param roleId the value for base_role_menu.ROLE_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}