package com.base.bean;

public class RoleUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_user.ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_user.USER_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_user.ROLE_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_user.ID
     *
     * @return the value of base_role_user.ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_user.ID
     *
     * @param id the value for base_role_user.ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_user.USER_ID
     *
     * @return the value of base_role_user.USER_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_user.USER_ID
     *
     * @param userId the value for base_role_user.USER_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_user.ROLE_ID
     *
     * @return the value of base_role_user.ROLE_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_user.ROLE_ID
     *
     * @param roleId the value for base_role_user.ROLE_ID
     *
     * @mbg.generated Fri Dec 21 09:40:40 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}