package com.base.bean;

import java.util.Set;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.NAME
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.REGION_ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.CREATE_USER_ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.IFDELETE
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    private Integer ifdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.ID
     *
     * @return the value of base_role.ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.ID
     *
     * @param id the value for base_role.ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.NAME
     *
     * @return the value of base_role.NAME
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.NAME
     *
     * @param name the value for base_role.NAME
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.REGION_ID
     *
     * @return the value of base_role.REGION_ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.REGION_ID
     *
     * @param regionId the value for base_role.REGION_ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.CREATE_USER_ID
     *
     * @return the value of base_role.CREATE_USER_ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.CREATE_USER_ID
     *
     * @param createUserId the value for base_role.CREATE_USER_ID
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.IFDELETE
     *
     * @return the value of base_role.IFDELETE
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public Integer getIfdelete() {
        return ifdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.IFDELETE
     *
     * @param ifdelete the value for base_role.IFDELETE
     *
     * @mbg.generated Fri Dec 21 09:36:35 CST 2018
     */
    public void setIfdelete(Integer ifdelete) {
        this.ifdelete = ifdelete;
    }
    
    private Set<RoleMenu> menuSet;

	public Set<RoleMenu> getMenuSet() {
		return menuSet;
	}

	public void setMenuSet(Set<RoleMenu> menuSet) {
		this.menuSet = menuSet;
	}

    
    
    
    
    
    
}